name:sample-workflow
on:
  push:
    branch: [master]

jobs:
  job1:
    run-on: ubuntu-latest
    steps:
    - name: check-out your repository under $GITHUB_WORKSPACE
      uses: action/checkout@v2
    - name: use echo command
      run: echo "sample-workflow"
